# path:
output_folder: "../outputs/"
pretrained_path: "../"

# model config: 
model: UNet
video_length: 16
image_size: [320, 512]

# beta schedule
beta_start: 0.0001
beta_end: 0.02
beta_schedule: "linear"

# model speedup
use_compile: False
use_fp16: True

# sample config:
seed: 3
run_time: 0
guidance_scale: 7.0
sample_method: 'ddpm'
num_sampling_steps: 250
text_prompt: [
              'a teddy bear walking on the street, high quality, 2k',

       ] 
